# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

index:
    path: /index
    defaults: { _controller: 'App\Controller\MonApp\FrontController::index'}

accueil:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: index
        permanent: true

landing:
    path: /landing
    defaults: { _controller: 'App\Controller\MonApp\FrontController::landing'}

elements:
    path: /elements
    defaults: { _controller: 'App\Controller\MonApp\FrontController::elements'}

generic:
    path: /generic
    defaults: { _controller: 'App\Controller\MonApp\FrontController::generic'}


contact:
    path: /contact
    defaults: { _controller: 'App\Controller\MonApp\FrontController::contact'}


